name: .NET
on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Check title PR
              run:
                # Check if the PR title contains "Hung"
                if [[ ${{ github.event.pull_request.title }} != *"Hung"* ]]; then
                  echo "PR title does not contain 'Hung'"
                  exit 1
                fi
            - name: Setup .NET Core
              uses : actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0.x
            - name: Restore dependencies
              run : dotnet restore
            - name: Build
              run : dotnet build --configuration Release --no-restore
            - name: Test
              run: dotnet test --no-restore --verbosity normal
            # auto deploy to host 192.168.2.212
            # - name: Deploy
            #   # host
            #   uses: appleboy/ssh-action@master
            #   with:
            #       host: ${{ secrets.HOST }}
            #       username: ${{ secrets.USERNAME }}
            #       password: ${{ secrets.PASSWORD }}
            #       port: ${{ secrets.PORT }}
            #       script: |
            #          # run docker and auto up version
            #          # cd project docker, read file docker-compose
            #          # Find the line with the image name and replace the version
            #          # Find service name : ke-collector and replace the version
            #             # docker-compose up -d --build                 
